import vazirFont from "@/constants/localFonts";
import "./globals.css";

export const metadata = {
  title: "next shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${vazirFont.variable} font-sans`}>{children}</body>
    </html>
  );
}
